[build]
  publish = "dist"
  command = "npm run build"
[[redirects]]
  from = "/messenger"
  force = true
  to = "/messenger"
  status = 302
[[redirects]]
  from = "/signin"
  to = "/"
  status = 302
[[redirects]]
  from = "/profile"
  to = "/"
  status = 302
[[redirects]]
  from = "/profile-password"
  to = "/"
  status = 302
[[redirects]]
  from = "/profile-settings"
  to = "/"
  status = 302
[[redirects]]
  from = "/*"
  to = "/"
  status = 302
[[redirects]]
  from = "/404"
  to = "/"
  status = 302
[[redirects]]
  from = "/500"
  to = "/"
  status = 302